#.github/workflows/code_integrity.yml
# This GitHub Action workflow automates the AI Code Integrity check on every pull request.

name: AI Code Integrity Check

on:
  pull_request:
    branches: [ main ]

jobs:
  hallucination-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          # We need the full history to get a list of changed files
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get changed files
        id: changed-files
        run: |
          # Get the list of changed files between the PR branch and the base branch
          FILES=$(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} | tr '\n' ',' | sed 's/,$//')
          echo "CHANGED_FILES=${FILES}" >> $GITHUB_OUTPUT

      - name: Run AI Code Integrity Check
        if: steps.changed-files.outputs.CHANGED_FILES!= ''
        run: |
          python main.py \
            --repo_path . \
            --changed_files "${{ steps.changed-files.outputs.CHANGED_FILES }}" \
            --github_repo "${{ github.repository }}" \
            --pr_number "${{ github.event.pull_request.number }}" \
            --github_token "${{ secrets.GITHUB_TOKEN }}"

